CREATE TABLE usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    nick VARCHAR(255) NOT NULL UNIQUE,
    contra VARCHAR(255) NOT NULL);